//
// Created by kira on 5/25/20.
//

#ifndef SMACH_LIB_VIDEO_TRANSMITTER_INCLUDE_VIDEO_TRANSMITTER_H_
#define SMACH_LIB_VIDEO_TRANSMITTER_INCLUDE_VIDEO_TRANSMITTER_H_

class VideoTransmitter {

};

#endif //SMACH_LIB_VIDEO_TRANSMITTER_INCLUDE_VIDEO_TRANSMITTER_H_
